# Generated by Django 4.2.3 on 2023-07-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha_nacimiento'),
        ),
    ]
