# Generated by Django 4.2.3 on 2023-08-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('precio', models.PositiveIntegerField(verbose_name='precio')),
                ('imagen', models.ImageField(upload_to='excusion/', verbose_name='imagen')),
                ('disponible', models.BooleanField(default=True, verbose_name='disponible')),
            ],
        ),
    ]
